"""enable pgvector extension

Revision ID: 95337697bb6f
Revises:
Create Date: 2026-08-13 13:30:01.313183

Not autogenerated: Alembic's autogenerate diffs table/column metadata, it has no concept of
"extensions" to detect, so this is a hand-written migration. It exists in Phase 1 — before any
table needs a `vector` column — so the RAG work in a later phase never has to touch
infrastructure, only add the columns/tables it needs against an already-vector-capable database.
"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "95337697bb6f"
down_revision: Sequence[str] | str | None = None
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None


def upgrade() -> None:
    # IF NOT EXISTS: the `pgvector/pgvector` Docker image (used in docker-compose.yml) already
    # ships the extension files, but doesn't enable it on the database by default — some
    # Postgres providers also pre-enable it per-database. Either way this stays a safe no-op.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")


def downgrade() -> None:
    op.execute("DROP EXTENSION IF EXISTS vector")
